 anyio
 argon2-cffi
 arrow
 async-lru
 babel
 beautifulsoup4
 bleach
 cffi
 comm
 control==0.9
 debugpy
 decorator
 dill
 executing
 fqdn
 git
 ipython
 isoduration
 jedi
 jinja2
 json5
 jsonmerge
 jupyter
 jupyterlab
 markupsafe
 mat4py
 matplotlib
 meson
 mistune
 moorpy
 ninja
 nlopt
 nlopt
 notebook
 numpy==1.23
 openmdao==3.27
 openpyxl
 openraft
 osqp==0.6.3
 overrides
 pandas
 parso
 patsy
 pexpect
 pip
 platformdirs
 psutil
 ptyprocess
 pyDOE3
 pygments
 python-json-logger
 pyzmq
 qdldl-python
 qtpy
 scikit-learn
 setuptools==64
 smt
 tornado    
 traitlets
 treon
 webencodings
 ruamel.yaml
 # pip:
 #   - dearpygui
 #   - marmot-agents

